# Generated by Django 5.0.7 on 2024-07-27 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeriesBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "order_label",
                    models.CharField(
                        blank=True,
                        help_text="If you want something other than its position in the series. E.g. “4.5”",
                        max_length=10,
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.book"
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.series"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("series", "order_label")},
            },
        ),
        migrations.AddField(
            model_name="series",
            name="books",
            field=models.ManyToManyField(
                blank=True,
                related_name="series",
                through="core.SeriesBook",
                to="core.book",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="series",
            unique_together={("user", "title")},
        ),
    ]
