# Generated by Django 5.0.7 on 2024-07-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_series_seriesbook_series_books_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="seriesbook",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="seriesbook",
            name="order",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="seriesbook",
            unique_together={("series", "order")},
        ),
    ]
