# Generated by Django 5.0.2 on 2024-02-29 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_author_book_bookexperience_bookcover_bookreading"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookcover",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="covers",
                to="core.book",
            ),
        ),
    ]
