# Generated by Django 5.0.7 on 2024-07-27 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_seriesbook_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="seriesbook",
            unique_together={("series", "book")},
        ),
    ]
