# Generated by Django 5.0.7 on 2024-07-28 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_seriesbook_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="series",
            options={"verbose_name_plural": "Series"},
        ),
    ]
