# Generated by Django 5.0.2 on 2024-02-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_author_slug_book_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
