# Generated by Django 5.0.2 on 2024-03-02 22:37

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_author_bio_alter_author_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookcover",
            name="image",
            field=models.ImageField(blank=True, upload_to=core.models.rename_image),
        ),
    ]
