# Generated by Django 5.0.2 on 2024-03-04 22:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_bookcover_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BookExperience",
            new_name="UserBook",
        ),
    ]
