# Generated by Django 5.0.3 on 2024-03-06 23:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_rename_bookexperience_userbook"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="author",
            name="date_of_death",
        ),
    ]
