# Generated by Django 5.1.1 on 2024-09-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_book_olid"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookcover",
            name="thumbnail_height",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookcover",
            name="thumbnail_width",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
