# Generated by Django 5.0.3 on 2024-03-07 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_remove_author_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookreading",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="readings",
                to="core.book",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="on_hand",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="book",
            name="status",
            field=models.CharField(
                choices=[
                    ("backlog", "Backlog"),
                    ("to-read", "To Read"),
                    ("reading", "Reading"),
                    ("finished", "Finished"),
                    ("dnf", "Did Not Finish"),
                ],
                default="backlog",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="UserBook",
        ),
    ]
