# Generated by Django 5.0.3 on 2024-03-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_bookreading_book_book_on_hand_book_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="published_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
