# Generated by Django 5.0.3 on 2024-03-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_book_published_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookcover",
            name="description",
            field=models.CharField(
                blank=True, help_text="E.g. “First edition,” etc.", max_length=100
            ),
        ),
    ]
