# Generated by Django 5.1.2 on 2024-10-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_bookcover_image_height_bookcover_image_width_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookcover",
            options={"ordering": ("order",)},
        ),
        migrations.AddField(
            model_name="bookcover",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
    ]
