# Generated by Django 5.1.2 on 2024-10-25 19:54

from django.db import migrations
from core.models import BookCover


def update_cover_order(self, schema_editor):
    for book in BookCover.objects.values_list("book", flat=True).distinct():
        covers = list(BookCover.objects.filter(book=book).order_by("updated_at"))
        for index, cover in enumerate(covers):
            cover.order = index + 1
            cover.save()


def revert_cover_order(apps, schema_editor):
    for cover in BookCover.objects.all():
        cover.order = 0
        cover.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_bookcover_options_bookcover_order"),
    ]

    operations = [migrations.RunPython(update_cover_order, revert_cover_order)]
