# Generated by Django 5.1.2 on 2024-10-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_update_cover_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="pages",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
