# Generated by Django 5.0.3 on 2024-03-13 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_rename_content_booknote_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booknote",
            options={"ordering": ["-created_at"]},
        ),
    ]
