# Generated by Django 5.1.2 on 2024-11-01 14:22

import core.image_helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_book_pages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookcover",
            name="image",
            field=models.ImageField(
                blank=True,
                default="",
                height_field="image_height",
                upload_to=core.image_helpers.rename_image,
                width_field="image_width",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bookcover",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                default="",
                height_field="thumbnail_height",
                upload_to=core.image_helpers.rename_image,
                width_field="thumbnail_width",
            ),
            preserve_default=False,
        ),
    ]
