# Generated by Django 5.0.3 on 2024-03-14 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_booknote_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookreading",
            options={"ordering": ["-created_at"]},
        ),
    ]
