# Generated by Django 5.0.3 on 2024-03-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_bookreading_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookreading",
            name="format",
            field=models.CharField(
                blank=True,
                choices=[
                    ("physical", "Physical"),
                    ("digital", "Digital"),
                    ("audio", "Audio"),
                ],
                max_length=20,
            ),
        ),
    ]
