# Generated by Django 5.1.2 on 2024-11-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_bookcover_image_alter_bookcover_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ManyToManyField(blank=True, to="core.author"),
        ),
    ]
