# Generated by Django 5.0.3 on 2024-03-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_bookreading_format"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="status",
            field=models.CharField(
                choices=[
                    ("wishlist", "Wishlist"),
                    ("backlog", "Backlog"),
                    ("to-read", "To Read"),
                    ("reading", "Reading"),
                    ("finished", "Finished"),
                    ("dnf", "Did Not Finish"),
                ],
                max_length=20,
            ),
        ),
    ]
