# Generated by Django 5.1.3 on 2024-11-25 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_book_unique_together_book_user_title_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookreading",
            name="rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
