# Generated by Django 5.0.3 on 2024-03-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_book_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookFormat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="book",
            name="on_hand",
        ),
        migrations.RemoveField(
            model_name="bookreading",
            name="format",
        ),
        migrations.AddField(
            model_name="book",
            name="format",
            field=models.ManyToManyField(
                blank=True,
                help_text="Choose as many as you have",
                null=True,
                related_name="books",
                to="core.bookformat",
            ),
        ),
    ]
