# Generated by Django 5.0.3 on 2024-03-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_book_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="olid",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
