# Generated by Django 5.0.3 on 2024-03-22 21:30

import core.image_helpers
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_bookcover_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookcover",
            name="image",
            field=imagekit.models.fields.ProcessedImageField(
                upload_to=core.image_helpers.rename_image
            ),
        ),
    ]
