# Generated by Django 5.0.3 on 2024-03-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_booktype"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookformat",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
