# Generated by Django 5.0.3 on 2024-03-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_bookformat_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookformat",
            name="description",
        ),
        migrations.AddField(
            model_name="booktype",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
