# Generated by Django 5.0.3 on 2024-03-28 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_remove_bookformat_description_booktype_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="books",
                to="core.booktype",
            ),
        ),
    ]
