# Generated by Django 5.0.3 on 2024-03-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_book_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="location",
            field=models.ManyToManyField(
                blank=True, related_name="books", to="core.booklocation"
            ),
        ),
    ]
