# Generated by Django 5.0.3 on 2024-03-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_book_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
