# Generated by Django 5.0.4 on 2024-04-20 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_book_archived"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookcover",
            options={"ordering": ["-updated_at"]},
        ),
    ]
