# Generated by Django 5.0.4 on 2024-04-22 00:32

import core.image_helpers
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_alter_bookcover_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookcover",
            name="thumbnail",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                null=True,
                upload_to=core.image_helpers.rename_image_thumbnail,
            ),
        ),
    ]
