# Generated by Django 5.0.4 on 2024-04-22 12:12

import core.image_helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_bookcover_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookcover",
            name="image",
            field=models.ImageField(upload_to=core.image_helpers.rename_image),
        ),
        migrations.AlterField(
            model_name="bookcover",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.image_helpers.rename_image_thumbnail,
            ),
        ),
    ]
