# Generated by Django 5.0.4 on 2024-04-22 12:51

import core.image_helpers
import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_alter_bookcover_image_alter_bookcover_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookcover",
            name="thumbnail",
        ),
        migrations.AlterField(
            model_name="bookcover",
            name="image",
            field=versatileimagefield.fields.VersatileImageField(
                upload_to=core.image_helpers.rename_image
            ),
        ),
    ]
