# Generated by Django 5.0.4 on 2024-04-22 21:11

import core.image_helpers
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_remove_bookcover_thumbnail_alter_bookcover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookcover",
            name="image",
            field=imagekit.models.fields.ProcessedImageField(
                upload_to=core.image_helpers.rename_image
            ),
        ),
    ]
