# Generated by Django 5.0.4 on 2024-04-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_squashed_0035_alter_bookcover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
