# Generated by Django 5.0.4 on 2024-04-24 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_alter_author_slug_alter_book_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookreading",
            options={"ordering": ["-start_date"]},
        ),
    ]
