# Generated by Django 5.0.4 on 2024-04-25 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_alter_bookreading_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookStatusChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_status", models.CharField(max_length=200)),
                ("new_status", models.CharField(max_length=200)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.book"
                    ),
                ),
            ],
        ),
    ]
