# Generated by Django 5.0.4 on 2024-04-25 12:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_bookstatuschange"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookstatuschange",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookstatuschange",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
