# Generated by Django 5.0.4 on 2024-04-25 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_bookstatuschange_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookstatuschange",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_changes",
                to="core.book",
            ),
        ),
    ]
