# Generated by Django 5.0.4 on 2024-04-25 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_alter_bookstatuschange_book"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookstatuschange",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="bookstatuschange",
            name="updated_at",
        ),
    ]
