# Generated by Django 5.0.4 on 2024-04-25 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_remove_bookstatuschange_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookstatuschange",
            options={"ordering": ["-changed_at"]},
        ),
    ]
