# Generated by Django 5.0.4 on 2024-04-28 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_author_user_book_user_alter_author_slug_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="author",
            unique_together={("user", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="book",
            unique_together={("user", "title")},
        ),
        migrations.RemoveField(
            model_name="author",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="book",
            name="slug",
        ),
    ]
