# Generated by Django 5.0.4 on 2024-04-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_alter_author_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="location",
            field=models.ManyToManyField(
                blank=True,
                help_text="For digital or audio books, choose the device or platform",
                related_name="books",
                to="core.booklocation",
            ),
        ),
    ]
