# Generated by Django 5.0.6 on 2024-06-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_user_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="imported",
            field=models.BooleanField(default=False),
        ),
    ]
