# Generated by Django 5.0.7 on 2024-07-10 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_book_imported"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="genres",
            field=models.ManyToManyField(
                blank=True,
                help_text="Choose as many as you like",
                related_name="books",
                to="core.bookgenre",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.bookgenre",
            ),
        ),
    ]
