# Generated by Django 5.0.7 on 2024-07-10 23:17

from django.db import migrations


def forwards(apps, schema_editor):
    Book = apps.get_model("core", "Book")

    for book in Book.objects.all():
        if book.genre:
            book.genres.add(book.genre)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_book_genres_alter_book_genre"),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
