# Generated by Django 5.0.7 on 2024-07-10 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_auto_20240710_1917"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="genre",
        ),
    ]
