# Generated by Django 5.0.7 on 2024-07-14 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_alter_bookgenre_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="genres",
            new_name="genre",
        ),
    ]
