# Generated by Django 5.0.7 on 2024-07-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_changelog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="changelog",
            options={
                "ordering": ["-date"],
                "verbose_name": "Changelog Entry",
                "verbose_name_plural": "Changelog Entries",
            },
        ),
        migrations.AlterField(
            model_name="changelog",
            name="details",
            field=models.TextField(blank=True),
        ),
    ]
