# Generated by Django 5.0.7 on 2024-07-16 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_alter_changelog_options_alter_changelog_details"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="changelog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Changelog Entry",
                "verbose_name_plural": "Changelog Entries",
            },
        ),
    ]
