# Generated by Django 5.0.7 on 2024-07-29 23:43

import core.image_helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_adjust_timezone_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookcover",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="bookcover",
            name="image",
            field=models.ImageField(upload_to=core.image_helpers.rename_image),
        ),
    ]
