# Generated by Django 5.0.7 on 2024-07-30 22:25

import core.image_helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_alter_bookcover_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookcover",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=core.image_helpers.rename_image
            ),
        ),
    ]
